services:
  master:
    image: locustio/locust
    container_name: locust-master
    ports:
      - "8089:8089"  # Web UI port
      - "5557:5557"  # Port for worker communication
      - "5558:5558"  # Port for worker communication
    volumes:
      - ./load-test/local_load_test/:/local_load_test # Mount the current directory to the container
    command: >
      -f /local_load_test/load_test.py --master

  worker:
    image: locustio/locust
    container_name: locust-worker
    volumes:
      - ./load-test/local_load_test/:/local_load_test # Mount the current directory to the container
    command: >
      -f /local_load_test/load_test.py --worker --master-host master

     
